using Microsoft.EntityFrameworkCore;
using Qalam.Data.Entity.Quran;
using Qalam.Infrastructure.context;

namespace Qalam.Infrastructure.Seeding;

public class QuranSurahsSeeder
{
    public static async Task SeedAsync(ApplicationDBContext context)
    {
        if (!await SeederHelper.HasAnyDataAsync(context.QuranSurahs))
        {
            var surahs = new List<QuranSurah>
            {
                new() { SurahNumber = 1, NameAr = "الفاتحة", NameEn = "Al-Fatihah", AyahCount = 7, PartNumber = 1 },
                new() { SurahNumber = 2, NameAr = "البقرة", NameEn = "Al-Baqarah", AyahCount = 286, PartNumber = 1 },
                new() { SurahNumber = 3, NameAr = "آل عمران", NameEn = "Ali 'Imran", AyahCount = 200, PartNumber = 3 },
                new() { SurahNumber = 4, NameAr = "النساء", NameEn = "An-Nisa", AyahCount = 176, PartNumber = 4 },
                new() { SurahNumber = 5, NameAr = "المائدة", NameEn = "Al-Ma'idah", AyahCount = 120, PartNumber = 6 },
                new() { SurahNumber = 6, NameAr = "الأنعام", NameEn = "Al-An'am", AyahCount = 165, PartNumber = 7 },
                new() { SurahNumber = 7, NameAr = "الأعراف", NameEn = "Al-A'raf", AyahCount = 206, PartNumber = 8 },
                new() { SurahNumber = 8, NameAr = "الأنفال", NameEn = "Al-Anfal", AyahCount = 75, PartNumber = 9 },
                new() { SurahNumber = 9, NameAr = "التوبة", NameEn = "At-Tawbah", AyahCount = 129, PartNumber = 10 },
                new() { SurahNumber = 10, NameAr = "يونس", NameEn = "Yunus", AyahCount = 109, PartNumber = 11 },
                new() { SurahNumber = 11, NameAr = "هود", NameEn = "Hud", AyahCount = 123, PartNumber = 11 },
                new() { SurahNumber = 12, NameAr = "يوسف", NameEn = "Yusuf", AyahCount = 111, PartNumber = 12 },
                new() { SurahNumber = 13, NameAr = "الرعد", NameEn = "Ar-Ra'd", AyahCount = 43, PartNumber = 13 },
                new() { SurahNumber = 14, NameAr = "إبراهيم", NameEn = "Ibrahim", AyahCount = 52, PartNumber = 13 },
                new() { SurahNumber = 15, NameAr = "الحجر", NameEn = "Al-Hijr", AyahCount = 99, PartNumber = 14 },
                new() { SurahNumber = 16, NameAr = "النحل", NameEn = "An-Nahl", AyahCount = 128, PartNumber = 14 },
                new() { SurahNumber = 17, NameAr = "الإسراء", NameEn = "Al-Isra", AyahCount = 111, PartNumber = 15 },
                new() { SurahNumber = 18, NameAr = "الكهف", NameEn = "Al-Kahf", AyahCount = 110, PartNumber = 15 },
                new() { SurahNumber = 19, NameAr = "مريم", NameEn = "Maryam", AyahCount = 98, PartNumber = 16 },
                new() { SurahNumber = 20, NameAr = "طه", NameEn = "Taha", AyahCount = 135, PartNumber = 16 },
                new() { SurahNumber = 21, NameAr = "الأنبياء", NameEn = "Al-Anbya", AyahCount = 112, PartNumber = 17 },
                new() { SurahNumber = 22, NameAr = "الحج", NameEn = "Al-Hajj", AyahCount = 78, PartNumber = 17 },
                new() { SurahNumber = 23, NameAr = "المؤمنون", NameEn = "Al-Mu'minun", AyahCount = 118, PartNumber = 18 },
                new() { SurahNumber = 24, NameAr = "النور", NameEn = "An-Nur", AyahCount = 64, PartNumber = 18 },
                new() { SurahNumber = 25, NameAr = "الفرقان", NameEn = "Al-Furqan", AyahCount = 77, PartNumber = 18 },
                new() { SurahNumber = 26, NameAr = "الشعراء", NameEn = "Ash-Shu'ara", AyahCount = 227, PartNumber = 19 },
                new() { SurahNumber = 27, NameAr = "النمل", NameEn = "An-Naml", AyahCount = 93, PartNumber = 19 },
                new() { SurahNumber = 28, NameAr = "القصص", NameEn = "Al-Qasas", AyahCount = 88, PartNumber = 20 },
                new() { SurahNumber = 29, NameAr = "العنكبوت", NameEn = "Al-'Ankabut", AyahCount = 69, PartNumber = 20 },
                new() { SurahNumber = 30, NameAr = "الروم", NameEn = "Ar-Rum", AyahCount = 60, PartNumber = 21 },
                new() { SurahNumber = 31, NameAr = "لقمان", NameEn = "Luqman", AyahCount = 34, PartNumber = 21 },
                new() { SurahNumber = 32, NameAr = "السجدة", NameEn = "As-Sajdah", AyahCount = 30, PartNumber = 21 },
                new() { SurahNumber = 33, NameAr = "الأحزاب", NameEn = "Al-Ahzab", AyahCount = 73, PartNumber = 21 },
                new() { SurahNumber = 34, NameAr = "سبأ", NameEn = "Saba", AyahCount = 54, PartNumber = 22 },
                new() { SurahNumber = 35, NameAr = "فاطر", NameEn = "Fatir", AyahCount = 45, PartNumber = 22 },
                new() { SurahNumber = 36, NameAr = "يس", NameEn = "Ya-Sin", AyahCount = 83, PartNumber = 22 },
                new() { SurahNumber = 37, NameAr = "الصافات", NameEn = "As-Saffat", AyahCount = 182, PartNumber = 23 },
                new() { SurahNumber = 38, NameAr = "ص", NameEn = "Sad", AyahCount = 88, PartNumber = 23 },
                new() { SurahNumber = 39, NameAr = "الزمر", NameEn = "Az-Zumar", AyahCount = 75, PartNumber = 23 },
                new() { SurahNumber = 40, NameAr = "غافر", NameEn = "Ghafir", AyahCount = 85, PartNumber = 24 },
                new() { SurahNumber = 41, NameAr = "فصلت", NameEn = "Fussilat", AyahCount = 54, PartNumber = 24 },
                new() { SurahNumber = 42, NameAr = "الشورى", NameEn = "Ash-Shuraa", AyahCount = 53, PartNumber = 25 },
                new() { SurahNumber = 43, NameAr = "الزخرف", NameEn = "Az-Zukhruf", AyahCount = 89, PartNumber = 25 },
                new() { SurahNumber = 44, NameAr = "الدخان", NameEn = "Ad-Dukhan", AyahCount = 59, PartNumber = 25 },
                new() { SurahNumber = 45, NameAr = "الجاثية", NameEn = "Al-Jathiyah", AyahCount = 37, PartNumber = 25 },
                new() { SurahNumber = 46, NameAr = "الأحقاف", NameEn = "Al-Ahqaf", AyahCount = 35, PartNumber = 26 },
                new() { SurahNumber = 47, NameAr = "محمد", NameEn = "Muhammad", AyahCount = 38, PartNumber = 26 },
                new() { SurahNumber = 48, NameAr = "الفتح", NameEn = "Al-Fath", AyahCount = 29, PartNumber = 26 },
                new() { SurahNumber = 49, NameAr = "الحجرات", NameEn = "Al-Hujurat", AyahCount = 18, PartNumber = 26 },
                new() { SurahNumber = 50, NameAr = "ق", NameEn = "Qaf", AyahCount = 45, PartNumber = 26 },
                new() { SurahNumber = 51, NameAr = "الذاريات", NameEn = "Adh-Dhariyat", AyahCount = 60, PartNumber = 26 },
                new() { SurahNumber = 52, NameAr = "الطور", NameEn = "At-Tur", AyahCount = 49, PartNumber = 27 },
                new() { SurahNumber = 53, NameAr = "النجم", NameEn = "An-Najm", AyahCount = 62, PartNumber = 27 },
                new() { SurahNumber = 54, NameAr = "القمر", NameEn = "Al-Qamar", AyahCount = 55, PartNumber = 27 },
                new() { SurahNumber = 55, NameAr = "الرحمن", NameEn = "Ar-Rahman", AyahCount = 78, PartNumber = 27 },
                new() { SurahNumber = 56, NameAr = "الواقعة", NameEn = "Al-Waqi'ah", AyahCount = 96, PartNumber = 27 },
                new() { SurahNumber = 57, NameAr = "الحديد", NameEn = "Al-Hadid", AyahCount = 29, PartNumber = 27 },
                new() { SurahNumber = 58, NameAr = "المجادلة", NameEn = "Al-Mujadila", AyahCount = 22, PartNumber = 28 },
                new() { SurahNumber = 59, NameAr = "الحشر", NameEn = "Al-Hashr", AyahCount = 24, PartNumber = 28 },
                new() { SurahNumber = 60, NameAr = "الممتحنة", NameEn = "Al-Mumtahanah", AyahCount = 13, PartNumber = 28 },
                new() { SurahNumber = 61, NameAr = "الصف", NameEn = "As-Saf", AyahCount = 14, PartNumber = 28 },
                new() { SurahNumber = 62, NameAr = "الجمعة", NameEn = "Al-Jumu'ah", AyahCount = 11, PartNumber = 28 },
                new() { SurahNumber = 63, NameAr = "المنافقون", NameEn = "Al-Munafiqun", AyahCount = 11, PartNumber = 28 },
                new() { SurahNumber = 64, NameAr = "التغابن", NameEn = "At-Taghabun", AyahCount = 18, PartNumber = 28 },
                new() { SurahNumber = 65, NameAr = "الطلاق", NameEn = "At-Talaq", AyahCount = 12, PartNumber = 28 },
                new() { SurahNumber = 66, NameAr = "التحريم", NameEn = "At-Tahrim", AyahCount = 12, PartNumber = 28 },
                new() { SurahNumber = 67, NameAr = "الملك", NameEn = "Al-Mulk", AyahCount = 30, PartNumber = 29 },
                new() { SurahNumber = 68, NameAr = "القلم", NameEn = "Al-Qalam", AyahCount = 52, PartNumber = 29 },
                new() { SurahNumber = 69, NameAr = "الحاقة", NameEn = "Al-Haqqah", AyahCount = 52, PartNumber = 29 },
                new() { SurahNumber = 70, NameAr = "المعارج", NameEn = "Al-Ma'arij", AyahCount = 44, PartNumber = 29 },
                new() { SurahNumber = 71, NameAr = "نوح", NameEn = "Nuh", AyahCount = 28, PartNumber = 29 },
                new() { SurahNumber = 72, NameAr = "الجن", NameEn = "Al-Jinn", AyahCount = 28, PartNumber = 29 },
                new() { SurahNumber = 73, NameAr = "المزمل", NameEn = "Al-Muzzammil", AyahCount = 20, PartNumber = 29 },
                new() { SurahNumber = 74, NameAr = "المدثر", NameEn = "Al-Muddaththir", AyahCount = 56, PartNumber = 29 },
                new() { SurahNumber = 75, NameAr = "القيامة", NameEn = "Al-Qiyamah", AyahCount = 40, PartNumber = 29 },
                new() { SurahNumber = 76, NameAr = "الإنسان", NameEn = "Al-Insan", AyahCount = 31, PartNumber = 29 },
                new() { SurahNumber = 77, NameAr = "المرسلات", NameEn = "Al-Mursalat", AyahCount = 50, PartNumber = 29 },
                new() { SurahNumber = 78, NameAr = "النبأ", NameEn = "An-Naba", AyahCount = 40, PartNumber = 30 },
                new() { SurahNumber = 79, NameAr = "النازعات", NameEn = "An-Nazi'at", AyahCount = 46, PartNumber = 30 },
                new() { SurahNumber = 80, NameAr = "عبس", NameEn = "Abasa", AyahCount = 42, PartNumber = 30 },
                new() { SurahNumber = 81, NameAr = "التكوير", NameEn = "At-Takwir", AyahCount = 29, PartNumber = 30 },
                new() { SurahNumber = 82, NameAr = "الإنفطار", NameEn = "Al-Infitar", AyahCount = 19, PartNumber = 30 },
                new() { SurahNumber = 83, NameAr = "المطففين", NameEn = "Al-Mutaffifin", AyahCount = 36, PartNumber = 30 },
                new() { SurahNumber = 84, NameAr = "الإنشقاق", NameEn = "Al-Inshiqaq", AyahCount = 25, PartNumber = 30 },
                new() { SurahNumber = 85, NameAr = "البروج", NameEn = "Al-Buruj", AyahCount = 22, PartNumber = 30 },
                new() { SurahNumber = 86, NameAr = "الطارق", NameEn = "At-Tariq", AyahCount = 17, PartNumber = 30 },
                new() { SurahNumber = 87, NameAr = "الأعلى", NameEn = "Al-A'la", AyahCount = 19, PartNumber = 30 },
                new() { SurahNumber = 88, NameAr = "الغاشية", NameEn = "Al-Ghashiyah", AyahCount = 26, PartNumber = 30 },
                new() { SurahNumber = 89, NameAr = "الفجر", NameEn = "Al-Fajr", AyahCount = 30, PartNumber = 30 },
                new() { SurahNumber = 90, NameAr = "البلد", NameEn = "Al-Balad", AyahCount = 20, PartNumber = 30 },
                new() { SurahNumber = 91, NameAr = "الشمس", NameEn = "Ash-Shams", AyahCount = 15, PartNumber = 30 },
                new() { SurahNumber = 92, NameAr = "الليل", NameEn = "Al-Layl", AyahCount = 21, PartNumber = 30 },
                new() { SurahNumber = 93, NameAr = "الضحى", NameEn = "Ad-Duhaa", AyahCount = 11, PartNumber = 30 },
                new() { SurahNumber = 94, NameAr = "الشرح", NameEn = "Ash-Sharh", AyahCount = 8, PartNumber = 30 },
                new() { SurahNumber = 95, NameAr = "التين", NameEn = "At-Tin", AyahCount = 8, PartNumber = 30 },
                new() { SurahNumber = 96, NameAr = "العلق", NameEn = "Al-'Alaq", AyahCount = 19, PartNumber = 30 },
                new() { SurahNumber = 97, NameAr = "القدر", NameEn = "Al-Qadr", AyahCount = 5, PartNumber = 30 },
                new() { SurahNumber = 98, NameAr = "البينة", NameEn = "Al-Bayyinah", AyahCount = 8, PartNumber = 30 },
                new() { SurahNumber = 99, NameAr = "الزلزلة", NameEn = "Az-Zalzalah", AyahCount = 8, PartNumber = 30 },
                new() { SurahNumber = 100, NameAr = "العاديات", NameEn = "Al-'Adiyat", AyahCount = 11, PartNumber = 30 },
                new() { SurahNumber = 101, NameAr = "القارعة", NameEn = "Al-Qari'ah", AyahCount = 11, PartNumber = 30 },
                new() { SurahNumber = 102, NameAr = "التكاثر", NameEn = "At-Takathur", AyahCount = 8, PartNumber = 30 },
                new() { SurahNumber = 103, NameAr = "العصر", NameEn = "Al-'Asr", AyahCount = 3, PartNumber = 30 },
                new() { SurahNumber = 104, NameAr = "الهمزة", NameEn = "Al-Humazah", AyahCount = 9, PartNumber = 30 },
                new() { SurahNumber = 105, NameAr = "الفيل", NameEn = "Al-Fil", AyahCount = 5, PartNumber = 30 },
                new() { SurahNumber = 106, NameAr = "قريش", NameEn = "Quraysh", AyahCount = 4, PartNumber = 30 },
                new() { SurahNumber = 107, NameAr = "الماعون", NameEn = "Al-Ma'un", AyahCount = 7, PartNumber = 30 },
                new() { SurahNumber = 108, NameAr = "الكوثر", NameEn = "Al-Kawthar", AyahCount = 3, PartNumber = 30 },
                new() { SurahNumber = 109, NameAr = "الكافرون", NameEn = "Al-Kafirun", AyahCount = 6, PartNumber = 30 },
                new() { SurahNumber = 110, NameAr = "النصر", NameEn = "An-Nasr", AyahCount = 3, PartNumber = 30 },
                new() { SurahNumber = 111, NameAr = "المسد", NameEn = "Al-Masad", AyahCount = 5, PartNumber = 30 },
                new() { SurahNumber = 112, NameAr = "الإخلاص", NameEn = "Al-Ikhlas", AyahCount = 4, PartNumber = 30 },
                new() { SurahNumber = 113, NameAr = "الفلق", NameEn = "Al-Falaq", AyahCount = 5, PartNumber = 30 },
                new() { SurahNumber = 114, NameAr = "الناس", NameEn = "An-Nas", AyahCount = 6, PartNumber = 30 }
            };

            await context.QuranSurahs.AddRangeAsync(surahs);
            await context.SaveChangesAsync();
        }
    }
}
