using MediatR;
using Qalam.Core.Bases;
using Qalam.Data.Results;

namespace Qalam.Core.Features.Authentication.Commands.Login
{
    public class LoginCommand : IRequest<Response<JwtAuthResult>>
    {
        /// <summary>
        /// User's username or email address for authentication
        /// </summary>
        public string? UserNameOrEmail { get; set; }
        public string? Password { get; set; }

        // Device tracking for session management
        public string? DeviceId { get; set; }  // Optional: Generated by frontend
        public string? DeviceName { get; set; } // e.g., "iPhone 14 Pro", "Chrome on Windows"

        /// <summary>Optional FCM / push device token to register on successful login.</summary>
        public string? DeviceToken { get; set; }

        /// <summary>ios | android | web — defaults to android when DeviceToken is set.</summary>
        public string? DeviceTokenPlatform { get; set; }

        public string? AppVersion { get; set; }
    }
}

